# Generated by Django 2.0 on 2018-04-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180425_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tag_names',
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
