# Generated by Django 2.0 on 2018-04-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180425_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tag_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
