# Generated by Django 2.0 on 2018-05-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_question_ans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='qid',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
